#!/bin/sh
# chkconfig: 2345 90 10
# description: Start or stop the crysadm server
#
### BEGIN INIT INFO
# Provides: crysadm
# Required-Start: $network $syslog
# Required-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Start or stop the crysadm server
### END INIT INFO

# Author: monokoo

name=Crysadm
BIN1=/opt/crysadm/crysadm/crysadm_helper.py
BIN2=/opt/crysadm/crysadm/crysadm.py


start(){
    /usr/local/bin/python3.4 $BIN1 >> /tmp/error 2>&1 &
    /usr/local/bin/python3.4 $BIN2 >> /tmp/error 2>&1 &
    RETVAL=$?
    if [ "$RETVAL" = "0" ]; then
        echo "$name start success"
    else
        echo "$name start failed"
    fi
}

stop(){
    pid=`ps -ef | grep -v grep | grep -v ps | grep -i "crysadm_helper" | awk '{print $2}'`
    if [ ! -z $pid ]; then
        pkill python3.4
        RETVAL=$?
        if [ "$RETVAL" = "0" ]; then
            echo "$name stop success"
        else
            echo "$name stop failed"
        fi
    else
        echo "$name is not running"
        RETVAL=1
    fi
}

status(){
    pid=`ps -ef | grep -v grep | grep -v ps | grep -i "crysadm_helper" | awk '{print $2}'`
    if [ -z $pid ]; then
        echo "*********************"
        echo "$name is not running"
        echo "*********************"
        tail -f /tmp/error
        RETVAL=1
    else
        echo "******************************"
        echo "$name is running with PID $pid"
        echo "******************************"
        tail -f /tmp/error
        RETVAL=0
    fi
}

case "$1" in
'start')
    start
    ;;
'stop')
    stop
    ;;
'status')
    status
    ;;
'restart')
    stop
    start
    RETVAL=$?
    ;;
*)
    echo "Usage: $0 { start | stop | restart | status }"
    RETVAL=1
    ;;
esac
exit $RETVAL
